version: "3"

services:
  api:
    build: api
    env_file: .env
    network_mode: "host"
    restart: always

  dialogue:
    build: ya-dialogue
    env_file: .env
    network_mode: "host"
    restart: always

  tg-bot:
    build: tg-bot
    env_file: .env
    network_mode: "host"
    restart: always

  tg-parser:
    build: tg-parser
    env_file: .env
    network_mode: "host"
    restart: always
