"""empty message

Revision ID: 1c4f3eee2772
Revises: d1567c402929
Create Date: 2020-06-27 01:10:07.566074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4f3eee2772'
down_revision = 'd1567c402929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_verification', sa.Column('bot_type', sa.String(length=8), nullable=True))
    op.add_column('users_verification', sa.Column('bot_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_verification', 'bot_user_id')
    op.drop_column('users_verification', 'bot_type')
    # ### end Alembic commands ###
