"""empty message

Revision ID: 68da8b4fdce8
Revises: 03b2a76fa461
Create Date: 2020-06-27 17:03:35.223801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68da8b4fdce8'
down_revision = '03b2a76fa461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('message_old', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel'], ['users_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_channels', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users_channels', 'source_url')
    op.drop_table('tg_messages')
    # ### end Alembic commands ###
